data_berita_kampus = [
    {
      _id: 1,
      url_path: "berita/peresmian-gedung-baru",
      judul: "Peresmian Gedung Baru di Kampus XYZ",
      deskripsi:
        "Kampus XYZ meresmikan gedung baru untuk meningkatkan fasilitas belajar mengajar.",
      kategori: "Pembangunan",
      tanggal_publish: ISODate("2024-01-23T00:00:00Z"),
      penulis: "Nama Penulis 1",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "kampus",
        "XYZ",
        "resmi",
        "meresmikan",
        "gedung",
        "baru",
        "fasilitas",
        "belajar",
        "mengajar",
        "Nama Penulis 1",
        "dua puluh tiga",
        "januari",
        "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 2,
      judul: "Mahasiswa Kampus ABC Raih Prestasi Internasional",
      deskripsi:
        "Seorang mahasiswa dari Kampus ABC berhasil meraih prestasi di ajang kompetisi internasional.",
      kategori: "Prestasi Mahasiswa",
      tanggal_publish: ISODate("2024-01-22T00:00:00Z"),
      penulis: "Nama Penulis 2",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "mahasiswa",
        "kampus",
        "ABC",
        "berhasil",
        "meraih",
        "prestasi",
        "ajang",
        "kompetisi",
        "internasional",
        "Nama Penulis 2",
        "dua puluh dua",
        "januari",
        "dua ribu dua puluh empat",
      ]
    },
    {
      _id: 3,
      judul: "Peluncuran Program Beasiswa Kampus LMN",
      deskripsi:
        "Kampus LMN meluncurkan program beasiswa untuk mendukung mahasiswa berprestasi.",
      kategori: "Beasiswa",
      tanggal_publish: ISODate("2024-01-21T00:00:00Z"),
      penulis: "Nama Penulis 3",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "kampus",
        "LMN",
        "meluncurkan",
        "program",
        "beasiswa",
        "dukung",
        "mahasiswa",
        "berprestasi",
        "Nama Penulis 3",
        "dua puluh satu",
        "januari",
        "dua ribu dua puluh empat",
    ]
    },
    {
      _id: 4,
      judul: "Seminar Nasional Teknologi di Kampus PQR",
      deskripsi:
        "Kampus PQR mengadakan seminar nasional tentang perkembangan terkini dalam bidang teknologi.",
      kategori: "Seminar",
      tanggal_publish: ISODate("2024-01-20T00:00:00Z"),
      penulis: "Nama Penulis 4",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "kampus",
        "PQR",
        "adakan",
        "seminar",
        "nasional",
        "perkembangan",
        "terkini",
        "bidang",
        "teknologi",
        "Nama Penulis 4",
        "dua puluh",
        "januari",
        "dua ribu dua puluh empat",
    ]
    },
    {
      _id: 5,
      judul: "Program KKN Kampus UVW di Desa XYZ",
      deskripsi:
        "Mahasiswa Kampus UVW melaksanakan Program Kuliah Kerja Nyata (KKN) di Desa XYZ.",
      kategori: "KKN",
      tanggal_publish: ISODate("2024-01-10T00:00:00Z"),
      penulis: "Nama Penulis 5",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "mahasiswa",
        "kampus",
        "UVW",
        "melaksanakan",
        "program",
        "kuliah",
        "kerja",
        "nyata",
        "KKN",
        "desa",
        "XYZ",
        "Nama Penulis 5",
        "sepuluh",
        "januari",
        "dua ribu dua puluh empat",
      ]
    },
    {
      _id: 6,
      judul: "Penghargaan Dosen Terbaik Tahun Ini",
      deskripsi:
        "Seorang dosen di Kampus DEF meraih penghargaan sebagai dosen terbaik tahun ini.",
      kategori: "Penghargaan Dosen",
      tanggal_publish: ISODate("2024-01-18T00:00:00Z"),
      penulis: "Nama Penulis 6",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "dosen",
            "kampus",
            "DEF",
            "meraih",
            "penghargaan",
            "terbaik",
            "tahun",
            "ini",
            "Nama Penulis 6",
            "delapan belas",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 7,
      judul: "Festival Seni Budaya di Kampus GHI",
      deskripsi:
        "Kampus GHI menggelar festival seni budaya untuk memperkenalkan keberagaman budaya di kalangan mahasiswa.",
      kategori: "Seni Budaya",
      tanggal_publish: ISODate("2024-01-17T00:00:00Z"),
      penulis: "Nama Penulis 7",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "kampus",
        "GHI",
        "menggelar",
        "festival",
        "seni",
        "budaya",
        "perkenalkan",
        "keberagaman",
        "budaya",
        "mahasiswa",
        "Nama Penulis 7",
        "tujuh belas",
        "januari",
        "dua ribu dua puluh empat",
      ]
    },
    {
      _id: 8,
      judul: "Pelatihan Kewirausahaan untuk Mahasiswa",
      deskripsi:
        "Kampus JKL menyelenggarakan pelatihan kewirausahaan bagi mahasiswa untuk mengembangkan keterampilan bisnis.",
      kategori: "Kewirausahaan",
      tanggal_publish: ISODate("2024-01-16T00:00:00Z"),
      penulis: "Nama Penulis 8",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "kampus",
        "JKL",
        "menyelenggarakan",
        "pelatihan",
        "kewirausahaan",
        "mahasiswa",
        "keterampilan",
        "bisnis",
        "Nama Penulis 8",
        "enam belas",
        "januari",
        "dua ribu dua puluh empat",
      ]
    },
    {
      _id: 9,
      judul: "Penelitian Inovatif di Laboratorium Kampus MNO",
      deskripsi:
        "Tim peneliti di Kampus MNO berhasil menciptakan inovasi terbaru dalam penelitian mereka di laboratorium.",
      kategori: "Penelitian",
      tanggal_publish: ISODate("2024-01-17T00:00:00Z"),
      penulis: "Nama Penulis 9",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "tim",
            "peneliti",
            "kampus",
            "MNO",
            "berhasil",
            "menciptakan",
            "inovasi",
            "terbaru",
            "penelitian",
            "mereka",
            "laboratorium",
            "Nama Penulis 9",
            "tujuh belas",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 10,
      judul: "Turnamen Olahraga Antar Kampus Tahun Ini",
      deskripsi:
        "Kampus PQR menjadi tuan rumah turnamen olahraga antar kampus yang diikuti oleh berbagai institusi pendidikan tinggi.",
      kategori: "Olahraga",
      tanggal_publish: ISODate("2024-01-16T00:00:00Z"),
      penulis: "Nama Penulis 10",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "kampus",
        "PQR",
        "tuan",
        "rumah",
        "turnamen",
        "olahraga",
        "antar",
        "kampus",
        "diikuti",
        "berbagai",
        "institusi",
        "pendidikan",
        "tinggi",
        "Nama Penulis 10",
        "enam belas",
        "januari",
        "dua ribu dua puluh empat",
      ],
    },
    {
      _id: 11,
      judul: "Kuliah Umum oleh Ahli Ekonomi Terkemuka",
      deskripsi:
        "Ahli ekonomi terkemuka memberikan kuliah umum di Kampus ABC untuk mahasiswa dan masyarakat umum.",
      kategori: "Kuliah Umum",
      tanggal_publish: ISODate("2024-01-17T00:00:00Z"),
      penulis: "Nama Penulis 11",
      gambar: "https://picsum.photos/seed/picsum/200/300",
      metadata: [
        "ahli",
        "ekonomi",
        "terkemuka",
        "memberikan",
        "kuliah",
        "umum",
        "kampus",
        "ABC",
        "mahasiswa",
        "masyarakat",
        "umum",
        "Nama Penulis 11",
        "tujuh belas",
        "januari",
        "dua ribu dua puluh empat",
      ]
    },
    {
      _id: 12,
      judul: "Ajang Kompetisi Teknologi Inovatif Kampus UVW",
      deskripsi:
        "Kampus UVW mengadakan ajang kompetisi untuk proyek-proyek teknologi inovatif yang dikembangkan oleh mahasiswa.",
      kategori: "Kompetisi Teknologi",
      tanggal_publish: ISODate("2024-01-15T00:00:00Z"),
      penulis: "Nama Penulis 12",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "kampus",
            "UVW",
            "mengadakan",
            "ajang",
            "kompetisi",
            "proyek",
            "teknologi",
            "inovatif",
            "dikembangkan",
            "mahasiswa",
            "Nama Penulis 12",
            "lima belas",
            "januari",
            "dua ribu dua puluh empat",
        ]
    },
    {
      _id: 13,
      judul: "Acara Ramah Lingkungan di Kampus LMN",
      deskripsi:
        "Kampus LMN mengadakan acara untuk meningkatkan kesadaran lingkungan di kalangan mahasiswa.",
      kategori: "Lingkungan",
      tanggal_publish: ISODate("2024-01-20T00:00:00Z"),
      penulis: "Nama Penulis 13",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "kampus",
            "LMN",
            "mengadakan",
            "acara",
            "meningkatkan",
            "kesadaran",
            "lingkungan",
            "mahasiswa",
            "Nama Penulis 13",
            "dua puluh",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 14,
      judul: "Pengenalan Program Studi Baru di Kampus XYZ",
      deskripsi:
        "Kampus XYZ memperkenalkan program studi baru yang akan mulai berjalan pada semester depan.",
      kategori: "Program Studi",
      tanggal_publish: ISODate("2024-01-18T00:00:00Z"),
      penulis: "Nama Penulis 14",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "kampus",
            "XYZ",
            "memperkenalkan",
            "program",
            "studi",
            "baru",
            "mulai",
            "berjalan",
            "semester",
            "depan",
            "Nama Penulis 14",
            "delapan belas",
            "januari",
            "dua ribu dua puluh empat",
        ]
    },
    {
      _id: 15,
      judul: "Kolaborasi Industri dan Akademi di Kampus DEF",
      deskripsi:
        "Kampus DEF menjalin kerjasama dengan industri untuk meningkatkan kualitas pendidikan dan penelitian.",
      kategori: "Kerjasama Industri",
      tanggal_publish: ISODate("2024-01-14T00:00:00Z"),
      penulis: "Nama Penulis 15",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "kampus",
            "DEF",
            "menjalin",
            "kerjasama",
            "industri",
            "meningkatkan",
            "kualitas",
            "pendidikan",
            "penelitian",
            "Nama Penulis 15",
            "empat belas",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 16,
      judul: "Kunjungan Tamu Besar di Kampus GHI",
      deskripsi:
        "Seorang tokoh terkenal mengunjungi Kampus GHI dan memberikan inspirasi kepada mahasiswa.",
      kategori: "Kunjungan Tamu",
      tanggal_publish: ISODate("2024-01-18T00:00:00Z"),
      penulis: "Nama Penulis 16",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "tokoh",
            "terkenal",
            "mengunjungi",
            "kampus",
            "GHI",
            "memberikan",
            "inspirasi",
            "mahasiswa",
            "Nama Penulis 16",
            "delapan belas",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 17,
      judul: "Workshop Teknik Kreatif di Kampus JKL",
      deskripsi:
        "Kampus JKL mengadakan workshop untuk mengembangkan kreativitas mahasiswa dalam bidang teknik.",
      kategori: "Workshop",
      tanggal_publish: ISODate("2024-01-19T00:00:00Z"),
      penulis: "Nama Penulis 17",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "kampus",
            "JKL",
            "mengadakan",
            "workshop",
            "mengembangkan",
            "kreativitas",
            "mahasiswa",
            "bidang",
            "teknik",
            "Nama Penulis 17",
            "sembilan belas",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 18,
      judul: "Kegiatan Sosial Mahasiswa di Kampus MNO",
      deskripsi:
        "Mahasiswa Kampus MNO aktif dalam kegiatan sosial untuk memberikan dampak positif bagi masyarakat sekitar.",
      kategori: "Kegiatan Sosial",
      tanggal_publish: ISODate("2024-01-20T00:00:00Z"),
      penulis: "Nama Penulis 18",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "mahasiswa",
            "kampus",
            "MNO",
            "aktif",
            "kegiatan",
            "sosial",
            "memberikan",
            "dampak",
            "positif",
            "masyarakat",
            "sekitar",
            "Nama Penulis 18",
            "dua puluh",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 19,
      judul: "Peluncuran Aplikasi Mobile Baru oleh Mahasiswa",
      deskripsi:
        "Sebuah tim mahasiswa meluncurkan aplikasi mobile inovatif yang mempermudah kehidupan sehari-hari.",
      kategori: "Inovasi Mahasiswa",
      tanggal_publish: ISODate("2024-01-21T00:00:00Z"),
      penulis: "Nama Penulis 19",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "tim",
            "mahasiswa",
            "meluncurkan",
            "aplikasi",
            "mobile",
            "inovatif",
            "mempermudah",
            "kehidupan",
            "sehari-hari",
            "Nama Penulis 19",
            "dua puluh satu",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
    {
      _id: 20,
      judul: "Sosialisasi Program Magang Kampus PQR",
      deskripsi:
        "Kampus PQR menyelenggarakan sosialisasi program magang untuk mahasiswa yang ingin mendapatkan pengalaman praktis.",
      kategori: "Magang",
      tanggal_publish: ISODate("2024-01-17T00:00:00Z"),
      penulis: "Nama Penulis 20",
      gambar: "https://picsum.photos/seed/picsum/200/300",
        metadata: [
            "kampus",
            "PQR",
            "menyelenggarakan",
            "sosialisasi",
            "program",
            "magang",
            "mahasiswa",
            "ingin",
            "mendapatkan",
            "pengalaman",
            "praktis",
            "Nama Penulis 20",
            "tujuh belas",
            "januari",
            "dua ribu dua puluh empat",
        ],
    },
  ];